<a href="https://colab.research.google.com/github/LucasPequenoSterzeck/Machine_Learning_LPS/blob/main/Previsibilidade_de_Moagem_em_Usinas_%5BPyTorch_Linear_Regression%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Teste para modelo que faz previsão de Moagem para Cálculo de Autonomia


<table>
  <tr>
    <th>Unidade</th>
    <th>Moagem</th>
    <th>Momento</th>
    <th>Apt. Produtivo[s.]</th>
    <th>Apt. Auxiliar[s.]</th>
    <th>Apt. Manutencao[s.]</th>
    <th>Apt. Perdido[s.]</th>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>25000</td>
    <td>10/07/2023 05:00:00</td>
    <td>2000</td>
    <td>1500</td>
    <td>400</td>
    <td>700</td>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>35000</td>
    <td>10/07/2023 06:00:00</td>
    <td>2800</td>
    <td>2000</td>
    <td>300</td>
    <td>500</td>
  </tr>
  <tr>
    <td>Charqueada</td>
    <td>15000</td>
    <td>10/07/2023 05:00:00</td>
    <td>1200</td>
    <td>900</td>
    <td>600</td>
    <td>300</td>
  </tr>
  <tr>
    <td>Charqueada</td>
    <td>10000</td>
    <td>10/07/2023 06:00:00</td>
    <td>800</td>
    <td>600</td>
    <td>700</td>
    <td>500</td>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>45000</td>
    <td>10/07/2023 07:00:00</td>
    <td>3200</td>
    <td>2400</td>
    <td>200</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>20000</td>
    <td>10/07/2023 08:00:00</td>
    <td>1600</td>
    <td>1200</td>
    <td>500</td>
    <td>700</td>
  </tr>
  <tr>
    <td>Charqueada</td>
    <td>8000</td>
    <td>10/07/2023 07:00:00</td>
    <td>600</td>
    <td>400</td>
    <td>800</td>
    <td>500</td>
  </tr>
  <tr>
    <td>Charqueada</td>
    <td>12000</td>
    <td>10/07/2023 08:00:00</td>
    <td>1000</td>
    <td>800</td>
    <td>700</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>30000</td>
    <td>10/07/2023 09:00:00</td>
    <td>2400</td>
    <td>1800</td>
    <td>300</td>
    <td>500</td>
  </tr>
  <tr>
    <td>Piracicaba</td>
    <td>40000</td>
    <td>10/07/2023 10:00:00</td>
    <td>3200</td>
    <td>2400</td>
    <td>200</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Charqueada</td>
    <td>20000</td>
    <td>10/07/2023 11:00:00</td>
    <td>1600</td>
    <td>1200</td>
    <td>500</td>
    <td>700</td>
  </tr>
</table>


In [179]:
import pandas as pd

data = {
    'Unidade': ['Piracicaba', 'Piracicaba', 'Charqueada', 'Charqueada', 'Piracicaba', 'Piracicaba', 'Charqueada', 'Charqueada', 'Piracicaba', 'Piracicaba', 'Charqueada'],
    'Moagem': [25000, 35000, 15000, 10000, 45000, 20000, 8000, 12000, 30000, 40000, 20000],
    'Momento': ['10/07/2023 05:00:00', '10/07/2023 06:00:00', '10/07/2023 05:00:00', '10/07/2023 06:00:00', '10/07/2023 07:00:00', '10/07/2023 08:00:00', '10/07/2023 07:00:00', '10/07/2023 08:00:00', '10/07/2023 09:00:00', '10/07/2023 10:00:00', '10/07/2023 11:00:00'],
    'Apt_Produtivo': [2000, 2800, 1200, 800, 3200, 1600, 600, 1000, 2400, 3200, 1600],
    'Apt_Auxiliar': [1500, 2000, 900, 600, 2400, 1200, 400, 800, 1800, 2400, 1200],
    'Apt_Manutencao': [400, 300, 600, 700, 200, 500, 800, 700, 300, 200, 500],
    'Apt_Perdido': [700, 500, 300, 500, 400, 700, 500, 400, 500, 400, 700]
}

df = pd.DataFrame(data)

# Exibindo o DataFrame
df

Unidade  Moagem              Momento  Apt_Produtivo  Apt_Auxiliar  \
0   Piracicaba   25000  10/07/2023 05:00:00           2000          1500   
1   Piracicaba   35000  10/07/2023 06:00:00           2800          2000   
2   Charqueada   15000  10/07/2023 05:00:00           1200           900   
3   Charqueada   10000  10/07/2023 06:00:00            800           600   
4   Piracicaba   45000  10/07/2023 07:00:00           3200          2400   
5   Piracicaba   20000  10/07/2023 08:00:00           1600          1200   
6   Charqueada    8000  10/07/2023 07:00:00            600           400   
7   Charqueada   12000  10/07/2023 08:00:00           1000           800   
8   Piracicaba   30000  10/07/2023 09:00:00           2400          1800   
9   Piracicaba   40000  10/07/2023 10:00:00           3200          2400   
10  Charqueada   20000  10/07/2023 11:00:00           1600          1200   

    Apt_Manutencao  Apt_Perdido  
0              400          700  
1              300          500  
2              600          300  
3              700          500  
4              200          400  
5              500          700  
6              800          500  
7              700          400  
8              300          500  
9              200          400  
10             500          700

In [159]:
# Criando variáveis
import torch
import numpy as np

inputs = torch.from_numpy(df.drop(columns=['Moagem','Unidade','Momento']).values).float()
target = torch.from_numpy(df.Moagem.values).float()

pesos = torch.rand([4], requires_grad=True, dtype=torch.float)
bias = torch.rand([1], requires_grad=True, dtype=torch.float)

# Declarando modelo
def modelo(entrada):
  return entrada @ pesos.t() + bias

predicao = modelo(inputs)

# Função de custo
def custo(predict, target):
  diff = (predict - target)
  return torch.sum(diff * diff) / diff.numel()

loss = custo(predicao, target)
loss.backward()
# Vendo gradientes:
print('Antigos pesos e bias:')
print(pesos)
print(bias)
print('Gradientes:')
print(pesos.grad)
print(bias.grad)
with torch.no_grad():
  pesos -= pesos.grad * 0.00001 # 1e-5
  bias -= bias.grad * 0.00001 # 1e-5
  pesos.grad.zero_()
  bias.grad.zero_()
print('Novos pesos e bias:')
print(pesos)
print(bias)
print(f'--> Estamos saindo de um erro de: {loss}, para...')

Antigos pesos e bias:
tensor([0.8443, 0.9752, 0.3666, 0.7079], requires_grad=True)
tensor([0.6702], requires_grad=True)
Gradientes:
tensor([-93720456., -69771600., -14956102., -20192640.])
tensor([-40377.2695])
Novos pesos e bias:
tensor([938.0489, 698.6912, 149.9276, 202.6343], requires_grad=True)
tensor([1.0740], requires_grad=True)
--> Estamos saindo de um erro de: 520111744.0, para...


In [160]:
epochs = 100
for i in range(epochs):
    preds = modelo(inputs)
    loss = custo(preds, target)
    loss.backward()
    with torch.no_grad():
        pesos -= pesos.grad * 1e-7
        bias -= bias.grad * 1e-7
        pesos.grad.zero_()
        bias.grad.zero_()
    if (i+1) % 10 == 0:
      print(f'Epoch [{i+1}/{epochs}], Loss: {loss}')

Epoch [10/100], Loss: 12003093.0
Epoch [20/100], Loss: 6163783.5
Epoch [30/100], Loss: 3680259.75
Epoch [40/100], Loss: 2561771.0
Epoch [50/100], Loss: 2057148.75
Epoch [60/100], Loss: 1828638.375
Epoch [70/100], Loss: 1724364.125
Epoch [80/100], Loss: 1676039.625
Epoch [90/100], Loss: 1652945.5
Epoch [100/100], Loss: 1641276.75


In [173]:
print('Comparando agora caso a caso, temos:')
for prev, real in zip(preds, target):
  print(f'Previsto {round(prev.item())} |vs| Real {round(real.item())}  [Diff.: {round(prev.item()-real.item())} - {round((prev.item()-real.item())/real.item()*100,2)}%]')

Comparando agora caso a caso, temos:
Previsto 25457 |vs| Real 25000  [Diff.: 457 - 1.83%]
Previsto 35637 |vs| Real 35000  [Diff.: 637 - 1.82%]
Previsto 15115 |vs| Real 15000  [Diff.: 115 - 0.77%]
Previsto 9573 |vs| Real 10000  [Diff.: -427 - -4.27%]
Previsto 41730 |vs| Real 45000  [Diff.: -3270 - -7.27%]
Previsto 20101 |vs| Real 20000  [Diff.: 101 - 0.5%]
Previsto 6536 |vs| Real 8000  [Diff.: -1464 - -18.3%]
Previsto 12628 |vs| Real 12000  [Diff.: 628 - 5.23%]
Previsto 30999 |vs| Real 30000  [Diff.: 999 - 3.33%]
Previsto 41730 |vs| Real 40000  [Diff.: 1730 - 4.32%]
Previsto 20101 |vs| Real 20000  [Diff.: 101 - 0.5%]


In [177]:
print(pesos)
print('\n[NOTA] Ao avaliar os pesos podemos observar que de forma geral existem correlações positivas e negativas entre variávei, sendo essas:')
print('\n[CORR +] Variáveis de Apontamento Produtivo e Auxiliar com correlação POSITIVA')
print('\n[CORR -] Variáveis de Apontamento Manutenção e Perdia com correlação NEGATIVA')

tensor([ 8.3801,  6.4288, -0.7426, -0.9277], requires_grad=True)

[NOTA] Ao avaliar os pesos podemos observar que de forma geral existem correlações positivas e negativas entre variávei, sendo essas:

[CORR +] Variáveis de Apontamento Produtivo e Auxiliar com correlação POSITIVA

[CORR -] Variáveis de Apontamento Manutenção e Perdia com correlação NEGATIVA


# Agora aplicando modelo segmentado por unidade

In [288]:
# Dicionario para conter modelos: NOME = (pesos, bias)
g_model = {}

# iniciando modelos:
for unidade in df.Unidade.unique():
  pesos = torch.rand([4], requires_grad=True, dtype=torch.float)
  bias = torch.rand([1], requires_grad=True, dtype=torch.float)
  g_model[unidade] = [pesos,bias]
g_model

{'Piracicaba': [tensor([0.7601, 0.5591, 0.8819, 0.1440], requires_grad=True),
  tensor([0.6576], requires_grad=True)],
 'Charqueada': [tensor([0.7858, 0.7615, 0.1264, 0.0638], requires_grad=True),
  tensor([0.8047], requires_grad=True)]}

In [303]:
# Declarando modelo
def modelo(entrada, pesos, bias):
  return entrada @ pesos.t() + bias

# Função de custo
def custo(predict, target):
  diff = (predict - target)
  return torch.sum(diff * diff) / diff.numel()

# Taxa de aprendizado:
learning_rate = 0.000000004

epochs = 10000
for unidade in df.Unidade.unique():
  print(f'\nIniciando treinamento de modelo da unidade {unidade}')
  input_unidade = torch.from_numpy(df[df.Unidade==unidade].drop(columns=['Moagem','Unidade','Momento']).values).float()
  target_unidade = torch.from_numpy(df[df.Unidade==unidade].Moagem.values).float()
  for i in range(epochs):
      preds = modelo(input_unidade, g_model[unidade][0], g_model[unidade][1])
      loss = custo(preds, target_unidade)
      loss.backward()
      with torch.no_grad():
          g_model[unidade][0] -= g_model[unidade][0].grad * learning_rate
          g_model[unidade][1] -= g_model[unidade][1].grad * learning_rate
          g_model[unidade][0].grad.zero_()
          g_model[unidade][1].grad.zero_()
      if (i+1) % 1000 == 0:
        print(f'Epoch [{i+1}/{epochs}], Loss: {loss}')


Iniciando treinamento de modelo da unidade Piracicaba
Epoch [1000/10000], Loss: 2319232.25
Epoch [2000/10000], Loss: 2319229.0
Epoch [3000/10000], Loss: 2319226.5
Epoch [4000/10000], Loss: 2319219.75
Epoch [5000/10000], Loss: 2319217.75
Epoch [6000/10000], Loss: 2319214.0
Epoch [7000/10000], Loss: 2319209.5
Epoch [8000/10000], Loss: 2319206.25
Epoch [9000/10000], Loss: 2319203.75
Epoch [10000/10000], Loss: 2319199.5

Iniciando treinamento de modelo da unidade Charqueada
Epoch [1000/10000], Loss: 3121.36572265625
Epoch [2000/10000], Loss: 3100.209716796875
Epoch [3000/10000], Loss: 3079.176025390625
Epoch [4000/10000], Loss: 3058.087158203125
Epoch [5000/10000], Loss: 3037.156005859375
Epoch [6000/10000], Loss: 3016.299560546875
Epoch [7000/10000], Loss: 2995.428466796875
Epoch [8000/10000], Loss: 2974.790283203125
Epoch [9000/10000], Loss: 2954.16015625
Epoch [10000/10000], Loss: 2933.57861328125


## Comparando previsões para Unidades:

In [304]:
for unidade in df.Unidade.unique():
  print(f'\n[INFO] Comparando previsões Unidade: {unidade}.')
  input_unidade = torch.from_numpy(df[df.Unidade==unidade].drop(columns=['Moagem','Unidade','Momento']).values).float()
  target_unidade = torch.from_numpy(df[df.Unidade==unidade].Moagem.values).float()
  preds = modelo(input_unidade, g_model[unidade][0], g_model[unidade][1])
  for prev, real in zip(preds, target):
    print(f'Previsto {round(prev.item())} |vs| Real {round(real.item())}  [Diff.: {round(prev.item()-real.item())} - {round((prev.item()-real.item())/real.item()*100,2)}%]')


[INFO] Comparando previsões Unidade: Piracicaba.
Previsto 24912 |vs| Real 25000  [Diff.: -88 - -0.35%]
Previsto 35018 |vs| Real 35000  [Diff.: 18 - 0.05%]
Previsto 42210 |vs| Real 15000  [Diff.: 27210 - 181.4%]
Previsto 19653 |vs| Real 10000  [Diff.: 9653 - 96.53%]
Previsto 31058 |vs| Real 45000  [Diff.: -13942 - -30.98%]
Previsto 42210 |vs| Real 20000  [Diff.: 22210 - 111.05%]

[INFO] Comparando previsões Unidade: Charqueada.
Previsto 14941 |vs| Real 25000  [Diff.: -10059 - -40.24%]
Previsto 10029 |vs| Real 35000  [Diff.: -24971 - -71.35%]
Previsto 7947 |vs| Real 15000  [Diff.: -7053 - -47.02%]
Previsto 12086 |vs| Real 10000  [Diff.: 2086 - 20.86%]
Previsto 19993 |vs| Real 45000  [Diff.: -25007 - -55.57%]
