<a href="https://colab.research.google.com/github/LucasPequenoSterzeck/Machine_Learning_LPS/blob/main/PyTorch_Jovian_ZeroToGANs%20/Class_01/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### Assignment Instructions (delete this cell before submission)
>
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html),
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
>
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Top 5 must now tensor functions

An short introduction about PyTorch and about the chosen functions.

- TORCH.TENSOR.POW
- TORCH.TENSOR.QSCHEME & QUANTIZE_PER_TENSOR
- TORCH.TENSOR.RESHAPE
- TORCH.TENSOR.ROUND
- TORCH.TENSOR.SPLIT

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - [TORCH.TENSOR.POW_](https://pytorch.org/docs/stable/generated/torch.Tensor.pow_.html#torch.Tensor.pow_)

Tensor.pow_(exponent)

In PyTorch, Tensor.pow() and Tensor.pow_() are two different methods for exponentiation.

This method returns a new tensor with each element raised to the power of the given exponent.
The original tensor remains unchanged.

Here's a simple example to illustrate the difference:

In [ ]:
tP = torch.tensor([2, 3, 4.])

# Example 1 Using Tensor.pow()
result = tP.pow(1)
print('Original tensor =', tP)
print('Tesnor using pow(1) =',tP)


Original tensor(tP) in POW function equals = tensor([ 4.,  9., 16.])
Original tesnor(tP) without any function equals = tensor([2., 3., 4.])


In [ ]:

# Example 2 Using Tensor.pow() with 2
test = torch.tensor([2, 3, 4.]).pow_(2)
print('New Tensor with pow(2)= ',test)


New Tensor with pow(2)=  tensor([ 4.,  9., 16.])


Here we use exponencialç multiplication with number 2, so the calculus for each item became like this:

2*2 = 4<br>
3*3 = 9<br>
4*4 = 16<br>

In [ ]:

# Example 2 Using Tensor.pow() with 3
test = torch.tensor([2, 3, 4.]).pow_(3)
print('New Tensor with pow(3)= ',test)


New Tensor with pow(3)=  tensor([ 8., 27., 64.])


Here we have a similar aproach, but in this case we use a 3 as expoent, so the calculus become something like this:

2*2*2 = 8<br>
3*3*3 = 27<br>
4*4*4 = 64<br>

We see that pow() use a matematical operatian in each item of the tensor.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 2 - [TORCH.TENSOR.QSCHEME](https://pytorch.org/docs/stable/generated/torch.Tensor.qscheme.html#torch.Tensor.qscheme)

Tensor.qscheme() → torch.qscheme

Returns the quantization scheme of a given QTensor.

Importante Note about this function: The qscheme() method is specifically designed to retrieve the quantization scheme of a quantized tensor (QTensor). In order to use qscheme(), you need to have a tensor that has undergone quantization using PyTorch's quantization functions.

So befor we use the QSCHEME() we need to use:
## [TORCH.TENSOR.QUANTIZE_PER_TENSOR](https://pytorch.org/docs/stable/generated/torch.quantize_per_tensor.html)
The torch.quantize_per_tensor() function is one of the methods available in PyTorch to quantize a tensor. It applies per-tensor quantization by determining a scaling factor (scale) and zero point (zero_point) to represent the tensor's values within a reduced range.
> In the practive: torch.quantize_per_tensor just turn each value into INT type

In [ ]:
# Quantize the tensor
tA = torch.tensor([[1,0.95],
                   [2,2.99],
                   [4.99,4.]], requires_grad=True)
scale = 0.1
zero_point = 0
quantized_tensor = torch.quantize_per_tensor(tA, scale, zero_point, dtype=torch.quint8)

quantized_tensor

tensor([[1., 1.],
        [2., 3.],
        [5., 4.]], size=(3, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=0)

**Note:** "affine" indicates that the quantization scheme uses an affine transformation to map floating-point values to quantized integer values

In [ ]:
# Example 1 - using qscheme()
qscheme = quantized_tensor.qscheme()
print(qscheme)  # Output: torch.per_tensor_affine


torch.per_tensor_affine


returns the quantization scheme used for the quantized_tensor. Since the output is torch.per_tensor_affine, it means that the tensor is quantized using a per-tensor affine approach with a single scale and zero-point for the entire tensor.

In [ ]:
# Example 2 - consulting qscheme

# Additional operations based on the quantization scheme
if qscheme == torch.per_tensor_affine:
    print("This is a per-tensor affine quantized tensor.")
elif qscheme == torch.per_channel_affine:
    print("This is a per-channel affine quantized tensor.")

This is a per-tensor affine quantized tensor.


The **torch.per_tensor_affine** quantization scheme is one of the quantization schemes available in PyTorch. Other schemes like **torch.per_tensor_symmetric** and **torch.per_channel_affine** also exist, and they use different quantization approaches to handle tensors.

In [ ]:
# Example 3 -
x = torch.tensor([0.5, 0.85, 0.9, 3.11])
zero_point = 0
scale = 1

# Quantitize the tensor element-wise
quantized_x = torch.round((x - zero_point) / scale)

print(quantized_x)

tensor([0., 1., 1., 3.])


The scale value depends on the specific quantization scheme and the range of values you want to represent with the quantized tensor.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - [TORCH.TENSOR.RESHAPE](https://pytorch.org/docs/stable/generated/torch.Tensor.reshape.html#torch.Tensor.reshape)

Tensor.reshape(*shape) → Tensor

Returns a tensor with the same data and number of elements as self but with the specified shape. This method returns a view if shape is compatible with the current shape. See torch.Tensor.view() on when it is possible to return a view.

In [ ]:
# Example 1 - working

tX = tA.reshape([2,3])

print(f'This is the original tensor(tA)\n{tA}\nWith Shape: {tA.shape}\n\nThis is the new reshaped tensor(tX):\n{tX}\nWith the new shape: {tX.shape}')

This is the original tensor(tA)
tensor([[1.0000, 0.9500],
        [2.0000, 2.9900],
        [4.9900, 4.0000]], requires_grad=True)
With Shape: torch.Size([3, 2])

This is the new reshaped tensor(tX):
tensor([[1.0000, 0.9500, 2.0000],
        [2.9900, 4.9900, 4.0000]], grad_fn=<ReshapeAliasBackward0>)
With the new shape: torch.Size([2, 3])


The reshape method enables data to be reshaped and rearranged without changing its contents, facilitating compatibility with various layers and model configurations. Properly using the reshape method is essential for preprocessing data and ensuring that tensors conform to the expected input shape of the model, thereby maximizing the effectiveness of the neural network during training and inference

In [ ]:
# Example 2
x = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped_x = x.reshape(2, 3)
print(x.shape)
print(reshaped_x.shape)

torch.Size([6])
torch.Size([2, 3])


The tensor x with 6 elements is reshaped into a 2x3 matrix.

In [ ]:
# Example 3
x = torch.randn(4, 2, 3)
reshaped_x = x.reshape(-1, 3)
print(x.shape)
print(reshaped_x.shape)

torch.Size([4, 2, 3])
torch.Size([8, 3])


 The tensor x of shape (4, 2, 3) is flattened into a matrix with 3 columns, and the number of rows is automatically computed to preserve the total number of elements.

In [ ]:
x = torch.arange(12)
reshaped_x = x.reshape(3, 2, 2)
print(x.shape)
print(reshaped_x.shape)

torch.Size([12])
torch.Size([3, 2, 2])


The tensor x with 12 elements is reshaped into a 3x2x2 matrix (3 dimensions), organizing the elements according to the specified dimensions.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - [TORCH.TENSOR.ROUND](https://pytorch.org/docs/stable/generated/torch.Tensor.round.html#torch.Tensor.round)

Tensor.round(decimals=0) → Tensor

Simply round the values of the tensor, let's aplly:

In [ ]:
# Example 1
x1 = torch.tensor([1.4, 2.7, 3.1, 4.9, 5.2])
rounded_x1 = x1.round()
print("Example 1 - Rounded Tensor:")
print(rounded_x1)

Example 1 - Rounded Tensor:
tensor([1., 3., 3., 5., 5.])


The tensor x with floating-point values is rounded to the nearest integers.

In [ ]:
# Example 2
x2 = torch.randn(2, 3)
rounded_x2 = x2.round()
print("\nExample 2 - Rounded Tensor:")
print(rounded_x2)


Example 2 - Rounded Tensor:
tensor([[-1., -1., -0.],
        [-1., -2., -1.]])


The tensor x of shape (2, 3) with random floating-point values is rounded to the nearest integers.

In [ ]:
# Example 3
x3 = torch.tensor([0.1, 0.6, 1.3, 2.8, 3.5])
rounded_x3 = x3.round()
print("\nExample 3 - Rounded Tensor:")
print(rounded_x3)


Example 3 - Rounded Tensor:
tensor([0., 1., 1., 3., 4.])


The tensor x with floating-point values is rounded to the nearest integers.

just like "round" function in python, this function is used to round item's of the tensor

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - [TORCH.TENSOR.SPLIT](https://pytorch.org/docs/stable/generated/torch.Tensor.split.html#torch.Tensor.split)

Tensor.split(split_size, dim=0)

torch.split is a PyTorch function used to split a tensor into multiple smaller tensors along a specified dimension. It allows for convenient data partitioning and is useful for tasks like data batching in machine learning.

In [ ]:
# Example 1
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
splits = torch.split(x, 2)
print("Example 1 - Splits:")
for split in splits:
    print(split)

Example 1 - Splits:
tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
tensor([7, 8])


In this example, the tensor x is split into equal-sized chunks of size 2 along its first dimension. The output displays three splits: [1, 2], [3, 4], and [5, 6], with the last split containing the remaining elements [7, 8].

In [ ]:
# Example 2
x = torch.randn(3, 4)
splits = torch.split(x, [1, 2, 1], dim=1)
print("\nExample 2 - Splits:")
for split in splits:
    print(split)


Example 2 - Splits:
tensor([[-0.1282],
        [-0.1708],
        [-0.1377]])
tensor([[ 1.8134, -0.1918],
        [ 2.0443, -0.2275],
        [ 1.2209,  0.3996]])
tensor([[ 0.6467],
        [ 0.4944],
        [-0.6341]])


Here, the tensor x of shape (3, 4) is split into three parts along the second dimension (columns). The sizes of the splits are specified as [1, 2, 1], resulting in three splits: the first split with one column, the second with two columns, and the third with one column.

In [ ]:
# Example 3
x = torch.arange(10)
splits = torch.split(x, 3, dim=0)
print("\nExample 3 - Splits:")
for split in splits:
    print(split)


Example 3 - Splits:
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([9])


In this example, the tensor x with values from 0 to 9 is split into chunks of size 3 along its first dimension (rows). The output displays four splits: [0, 1, 2], [3, 4, 5], [6, 7, 8], and [9], where the last split contains the remaining elements since the input tensor length is not divisible by 3.

The torch.split function takes the input tensor and either the number of equally-sized chunks to split or a list of sizes to define the size of each split. The result is a tuple containing the split tensors. If the input tensor size is not divisible by the specified chunk size, the last split will contain the remaining elements.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

**torch.tensor.pow:** This function computes the element-wise power of a tensor with a specified exponent. It is beneficial for mathematical calculations and element-wise transformations of tensors.

**torch.tensor.qscheme & torch.quantize_per_tensor:** These functions are part of PyTorch's quantization module, allowing users to understand the quantization scheme used for a quantized tensor. torch.quantize_per_tensor is used to quantize a floating-point tensor, while torch.tensor.qscheme helps determine the quantization scheme (e.g., per-tensor affine quantization) of a quantized tensor.

**torch.tensor.reshape:** The reshape method allows the alteration of the shape of a tensor without changing its contents. It is essential for correctly preparing data to fit into specific model architectures and layers.

**torch.tensor.round:** This function rounds the elements of a tensor to the nearest integers. It is useful for converting floating-point tensors to integers, especially when dealing with discrete values or for integer quantization.

**torch.tensor.split:** The split function is useful for partitioning a tensor into smaller tensors along a specified dimension. It provides a convenient way to divide data into batches or subsets, essential for training and processing large datasets.

These functions showcase the versatility and power of PyTorch in handling various tensor operations, enabling efficient computation and manipulation of data for deep learning and other numerical applications.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
